modLoader="javafml"
loaderVersion="[42,)"
license="MIT License"
issueTrackerURL="https://github.com/CAS-ual-TY/DonkeyTransportInc/issues"

[[mods]]
    modId="donkey_transport_inc"
    version="${file.jarVersion}"
    displayName="Donkey Transport Inc."
    displayURL="https://github.com/CAS-ual-TY/DonkeyTransportInc"
    logoFile="logo.png"
    credits="Thank you to Mojang, the MinecraftForge team and to all underappreciated donkeys."
    authors="CAS_ual_TY"
    description='''Hypnotize donkeys for item transport (#forgejam22 coding contest entry).

This mod is as great as it sounds. Disclaimer: There is no actual company or trade mark involved, this is a joke.

Steps on how to use this mod:
- You get the Donkey Hypnotizer™
- This item is spawned whenever a donkey is struck by lightning
- You mark waypoints with it
- You click the donkey to hypnotize it
- The donkey now goes to the first waypoint
- You slap the donkey and it goes to the next waypoint
- Pro tip: Use snowballs

Additional features:
- Donkeys with chests now interact with hoppers
- Press F3+B to see which hoppers a hypnotized donkey interacts with
'''
